#!/bin/sh
#
# $Header:  /lib/sv/sh/dep                               Exp $
# $Author: (c) 2015-6 tokiclover <tokiclover@gmail.com>  Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
# $Version: 1.4 2016/01/12 21:09:26                      Exp $
#

#
# ZSH compatibility
#
if [ -n "${ZSH_VERSION}" ]; then
	emulate sh
	NULLCMD=:
	setopt NO_GLOB_SUBST NULLGLOB SH_WORD_SPLIT
	disable -r end
elif [ -n "${BASH_VERSION}" ]; then
	shopt -qs nullglob
else
	case "$(set -o 2>/dev/NULL)" in
		(*posix*) set -o posix;;
	esac
fi

SV_CGROUP=0
export LC_ALL=C LANG=C
:	${name=${0##*/}}
:	${SV_LIBDIR:=${0%/sh/*}}
. "${0%/*}"/runscript-functions ||
	{ echo "Required file not found." >&2; exit 1; }
SV_DEPDIR="${SV_TMPDIR}/deps"

add_dep()
{
	local svc="${1}" dep="${2%:*}" DEP="${2#*:}"
	shift 2
	echo "${svc}:${dep}=\"${@}\""
	[ -n "${SVC_KEYWORD}" ] && echo "${svc}:keyword=\"${SVC_KEYWORD}\""
	[ -n "${SVC_PROVIDE}" ] && echo "${svc}:provide=\"${SVC_PROVIDE}\""
	[ -n "${SVC_TIMEOUT}" ] && echo "${svc}:timeout=\"${SVC_TIMEOUT}\""
	[ -n "${SVC_NOHANG}"  ] && echo "${svc}:nohang=\"${SVC_NOHANG}\""
}
dep_gen()
{
	local RC_OPTS SVC_DEBUG SVC_NAME SVC_NEED SVC_USE SVC_BEFORE SVC_AFTER name
	local dep SVC_NOHANG SVC_PROVIDE SVC_KEYWORD SVC_TIMEOUT

	SVC_NAME="${1}"
	__svc__="${SV_SVCDIR}/${1}"
	if   [ -d ${__svc__} ]; then
		SV_TYPE=sv
	elif [ -f ${__svc__} ]; then
		SV_TYPE=rs
	else
		return
	fi
	shift
	. ${SV_SVCDIR}/.opt/SVC_OPTIONS

	for dep in ${__SV_DEPS_ORDER__}; do
		eval add_dep "${SVC_NAME}" "${dep}" \${SVC_${dep#*:}} >&4
	done
}

dep_scan()
{
	local dir svc

	for dir in ${@:-${SV_SVCDIR}}; do
		cd ${dir}
		for svc in *; do
			dep_gen "${svc}"
		done
	done
}

svcdeps=${SV_DEPDIR}/svcdeps
if [ "${#}" = 0 ]; then
	exec 4>${svcdeps}
	dep_scan
else
	exec 4>${SV_DEPDIR}/tmp
	for svc; do
		[ -n "${SVCDEPS_UPDATE}" ] && sed "/^${svc}:/d" -i ${svcdeps}
		dep_gen "${svc}"
	done
	cat ${SV_DEPDIR}/tmp >>${svcdeps}
	rm -f ${SV_DEPDIR}/tmp
fi
exec 4>&-

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
