#!/bin/sh
#
# $Header:  /lib/sv/sh/init-stage                        Exp $
# $Author: (c) 2015-6 tokiclover <tokiclover@gmail.com>  Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
# $Version: 1.1 2016/07/14                               Exp $
#

:	${name=${0##*/}}
:	${SV_LIBDIR:=${0%/sh/*}}
source "${0%/*}"/runscript-functions ||
	{ echo "Required file not found." >&2; exit 1; }
source ${SV_SVCDIR}/.opt/SVC_BACKEND
source ${SV_SVCDIR}/.opt/sv.conf
umask 022

SV_CMD="${__SV_CMD__##*/}"

svc_init()
{
	local dir opt procfs OS_NAME="$(uname -s)"
	[ -w /etc/mtab ] || opt=-n

	procfs=proc
	case "${OS_NAME}" in
		(GNU/kFreeBSD) procfs=linprocfs;;
	esac

	if ! mountinfo --quiet /proc 2>${NULL}; then
		begin "Mounting /proc"
		mount ${opt} -t ${procfs} -o ${SYSFS_OPTS:-nodev} proc /proc
		end ${?}
	fi

	case "${OS_NAME}" in
		(Linux)
	if [ ! -d /run ]; then
		begin "Creating /run"
		mkdir -m 0755 -p /run
		end ${?}
	fi
	if ! mountinfo --quiet /run; then
		begin "Mounting /run"
		mount ${opt} -t tmpfs -o nodev,mode=755,size=${RUN_FS_SIZE:-1%} run /run
		end ${?}
	fi
		;;
	esac
}

svc_level()
{
	case "${1}" in
		(-0) ACTION=sysinit LEVEL=S;;
		(-1) ACTION=boot    LEVEL=S;;
		(-2)
		case "$(cat /proc/cmdline)" in
			(*nonetwork*) ACTION=nonetwork LEVEL=2;;
			(*single*)    ACTION=single  LEVEL=1;;
			(*default*|*) ACTION=default LEVEL=3;;
		esac;;
		(-3) ACTION=${ACTION:=shutdown} LEVEL=${LEVEL:=0};;
		(*) return;;
	esac
	export ACTION LEVEL

	if yesno ${RC_INIT_SYS:-YES}; then
		begin "${MSG:-System ${ACTION}}\n"
		RUNLEVEL=${LEVEL} rc ${ACTION}
		end ${?}
	fi
	[ -d "${SV_RUNDIR}" ] || svc_tmpdir

	case "${ACTION}" in
		(single|boot)
			${SV_LIBDIR}/sh/dep -v ${1} -d "${SV_SERVICE}/.${ACTION}"
			;;
	esac
}

svc_rsh()
{
:	${RS_SHELL:=${SHELL:-sh}}
	case "${RS_SHELL}" in
		(*sulogin) exec ${RS_SHELL} -p /dev/tty8;;
		(*sh) exec 2>&1; exec ${RS_SHELL} -aim  ;;
	esac
}

svc_shutdown()
{
	#
	# Service halt
	#
	begin "Stopping Stage-2"
	rs -2 stage stop
	eval ${__SVCCMD__} ${__SIGWDWN__-${__SIGEXIT__}} ${SV_RUNDIR}/*
	end "${?}"
	#
	# CGroup clean up
	#
	if  [ "${OS_NAME}" = "Linux" ]; then
		SVC_NAME="${SV_CMD}" cgroup_remove_service
	fi
	#
	# System halt
	#
	begin "Starting Stage-3"
	rs -3 --rs stage
	end "${?}"
}

svc_tmpdir()
{
	#
	# Handle read-only root-FS and/or static /service/
	#
	case "${SV_RUNDIR}" in
		("${SV_SERVICE}")
		;;
		(*/run/*|*/tmp/*)
		rm -f -r "${SV_TMPDIR}"
		mkdir -p "${SV_TMPDIR}"
		ln -fs "${SV_SERVICE}"/.[eol]* "${SV_RUNDIR}"
		;;
	esac
	mkdir -p "${SV_TMPDIR}"/down "${SV_TMPDIR}"/fail \
		"${SV_TMPDIR}"/pids "${SV_TMPDIR}"/star "${SV_TMPDIR}"/wait
	#
	# Initialization
	#
	echo "${__SV_NAM__}:${SV_CMD}" >"${SV_TMPDIR}"/sv
	OS_NAME=$(uname -s)
	env_sv OS_NAME

	#
	# Set up CGroup
	#
	if yesno ${SV_CGROUP:-YES}; then
		rs devfs start &
		rs sysfs start
		cgroup_start_sys
		case ${?} in
			(0) SV_CGROUP=Yes;;
			(*) SV_CGROUP=No ;;
		esac
		env_sv SV_CGROUP
	fi
}

case ${SV_CMD} in
	(runsvdir)
:	${SV_OPTS:=log:...........................................................}
	;;
esac

pidfile="${SV_TMPDIR}/${SV_CMD}.pid"
begin "Starting Init-Stage${1}\n"
if [ "${1}" = "-0" ]; then
	svc_tmpdir
	echo $$ >${pidfile}
	${__SV_CMD__} ${SV_RUNDIR} ${SV_OPTS} &
elif [ "${1}" = "-1" ]; then
	svc_init
	svc_level -0
	rs -0 --rs stage

	#
	# Try to bring up the device manager, like udev, as early as possible
	#
	if [ -e ${SV_SERVICE}/.${ACTION}/dev ]; then
		cp -HRpu ${SV_SERVICE}/.${ACTION}/dev ${SV_RUNDIR}
		echo $$ >${pidfile}
		${__SV_CMD__} ${SV_RUNDIR} ${SV_OPTS} &
	fi
	svc_level -1
	rs -1 --rs stage
elif [ "${1}" = "-2" ]; then
	#
	# Set up CGroup
	#
	if [ "${OS_NAME}" = "Linux" ]; then
		SVC_NAME="${SV_CMD}" cgroup_add_service
	fi
	svc_level -2
	#
	# Bring up what left and stage-2 assuming `svcscan'
	# is ready when the following pidfile is present
	#
	if [ -e "${pidfile}" ]; then
		kill -TERM $(cat ${pidfile}) 2>${NULL}
		rm ${pidfile}
	fi
	sh -c "source ${SV_LIBDIR}/sh/runscript-functions;
		svc_wait -E 1000 ${SV_CMD} ${pidfile};
		rs -1 stage; rs -2 stage;" &

	echo $$ >${pidfile}
	exec ${__SV_CMD__} ${SV_RUNDIR} ${SV_OPTS}
	#
	# Drop into a rescue shell
	#
	svc_rsh
elif [ "${1}" = "-3" ]; then
	svc_shutdown
	svc_level -3
fi
end "${?}"

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
