#!/bin/sh
#
# $Header:  /lib/sv/sh/init-stage-0                      Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

:	${name=${0##*/}}
source "${0%/*}"/sv-backend ||
{ echo "Required file not found." >&2; exit 1; }
svc_backend -i -C

[ -w /etc/mtab ] || opt=-n

procfs=proc
case "$(uname -s)" in
	(GNU/kFreeBSD) procfs=linprocfs;;
esac
if ! grep -Eq '/proc .*proc' /proc/mounts; then
	begin "Mounting /proc"
	mount ${opt} -t ${procfs} -o ${SYSFS_OPTS:-nodev} proc /proc
	end ${?}
fi

[ -d /run ] || exit 0
if ! grep -Eq '/run .*tmpfs' /proc/mounts; then
	begin "Mounting /run"
	mount ${opt} -t tmpfs -o nodev,mode=755,size=${RUN_FS_SIZE:-1%} run /run
	end ${?}
fi

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
