#!/bin/sh
#
# $Id:  @(#) init-stage    1.8 2017/01/18 21:09:26                    Exp $
# $C$:  Copyright (c) 2015-2017 tokiclover <tokiclover@gmail.com>     Exp $
# $L$:  2-clause/new/simplified BSD License                           Exp $
#

if [ -n "${ZSH_VERSION}" ]; then
	emulate sh
	NULLCMD=:
	setopt SH_WORD_SPLIT
	disable -r end
fi

:	${CONSOLE:=/dev/console}
:	${SV_SHELL:=${SHELL:-/bin/sh}}
svc_rsh()
{
	NULL=/dev/null
	SULOGIN="$(command -v sulogin)"
:	${SULOGIN_TTY:=/dev/tty8}
	if [ "${SV_SHELL##*/}" = "sulogin" ]; then
		exec ${SV_SHELL} -p /dev/tty8
	fi
	[ "${OS_NAME}" = "Linux" -a -x ${SULOGIN} ] && exec ${SULOGIN} -p ${SULOGIN_TTY}
	exec <${CONSOLE} >${CONSOLE}
	exec 2>&1
	exec ${SV_SHELL} -lim
	for sh in /bin/sh sh "/bin/busybox sh" "busybox sh" ${SHELLS}; do
		exec ${sh} -lim
	done
	echo "No functional shell found!!!" >&2
}

name="${0##*/}"
if [ "${name}" = "init-stage" ]; then
	SV_LIBDIR="${0%/sh/*}"
else
	name="init-stage"
:	${SV_LIBDIR:=/lib/sv}
fi
if ! . ${SV_LIBDIR}/sh/runscript-functions; then
	echo "Required file not found." >&2
	[ -n "${SV_OPTS}" ] && svc_rsh || exit 1
fi
:	${SV_SVCDIR:=/etc/sv}
. ${SV_LIBDIR}/opt/SVC_BACKEND
. ${SV_SVCDIR}.conf
umask 022

SV_CMD="${__SV_CMD__##*/}"
SVC_NAME="${SV_CMD}"

early_console()
{
	[ -d ${SV_LIBDIR}/cache ] || return

	local encoding='%@' args kbd_args=-a keymap consolefont
	if [ -e ${SV_LIBDIR}/cache/unicode ]; then
		encoding='%G' kbd_args=-u
	fi
	printf "\033${encoding}" >${CONSOLE}

	[ -c ${CONSOLE} ] && args="-C ${CONSOLE}"
	consolefont=${SV_LIBDIR}/cache/font+umap
	[ -s ${consolefont} ] && setfont ${args} ${consolefont} 2>${NULL}

	[ -n "${args}" ] && kbd_mode ${kbd_args} ${args}
	keymap=${SV_LIBDIR}/cache/keymap
	[ -s ${keymap} ] && loadkeys -q ${keymap} 2>${NULL}
}

svc_init()
{
	local dir opt procfs OS_NAME="$(uname -s)"
	[ -w /etc/mtab ] || opt=-n

	if   [ "${OS_NAME}" = "GNU/kFreeBSD" ]; then
		procfs=linprocfs
	else
		procfs=proc
	fi

	if ! mountinfo --quiet /proc 2>${NULL}; then
		begin "Mounting /proc"
		mount ${opt} -t ${procfs} -o ${SYSFS_OPTS:-nodev} proc /proc
		end ${?}
	fi

	if [ "${OS_NAME}" = "Linux" ]; then
	if [ ! -d /run ]; then
		begin "Creating /run"
		mkdir -m 0755 -p /run
		end ${?}
	fi
	if ! mountinfo --quiet /run; then
		begin "Mounting /run"
		mount ${opt} -t tmpfs -o nodev,mode=755,size=${RUN_FS_SIZE:-1%} run /run
		end ${?}
	fi
	fi # OS_NAME=Linux

	#
	# XXX: Add some insurance to get a few services started early (e.g. lvm
	#   needs /run/lock/lvm which is started before miscfs.) Who need lvm
	#   for `/var'? Nothing will ever... well, it will with some hassle.
	#
	for dir in /var/run /var/lock; do
		[ -L "${dir}" ] || continue
		dir="$(readlink ${dir})"
		case "${dir}" in
			(/run*)
			begin "Creating ${dir}"
			mkdir -m 0755 -p "${dir}"
			end ${?}
			;;
		esac
	done

	[ -d "${SV_RUNDIR}" ] || svc_tmpdir
}

svc_tmpdir()
{
	rm -fr "${SV_TMPDIR}"
	mkdir -p "${SV_TMPDIR}"
	ln -fs "${SV_LIBDIR}"/opt "${SV_RUNDIR}"/.opt
	[ -d ${SV_SVCDIR}/.env ] && cp -a ${SV_SVCDIR}/.env ${SV_TMPDIR}
	mkdir -p "${SV_TMPDIR}"/down "${SV_TMPDIR}"/deps "${SV_TMPDIR}"/fail \
		${SV_TMPDIR}/opts \
		"${SV_TMPDIR}"/pids "${SV_TMPDIR}"/star "${SV_TMPDIR}"/wait
	#
	# Initialization
	#
	OS_NAME="$(uname -s)"
	ENV_SVC OS_NAME

	#
	# Set up CGroup
	#
	if yesno ${SV_CGROUP:-YES} && [ -z "${SV_SYSTEM}" ]; then
		if /sbin/rs devfs start && /sbin/rs sysfs start; then
		cgroup_start_sys
		case ${?} in
			(0) SV_CGROUP=Yes;;
			(*) SV_CGROUP=No ;;
		esac
		else
		SV_CGROUP=FALSE
		fi
	else
		SV_CGROUP=DISABLE
	fi
	ENV_SVC SV_CGROUP
}

kill_svscan()
{
	local args cmd dir pid

	if [ "${OS_NAME}" =      "FreeBSD" ]; then
		args=-fl
	else
		args=-ax
	fi
	pgrep ${args} "${SV_CMD}" | \
	while read pid cmd dir args; do
		if [ "${dir}" = "${SV_RUNDIR}" ]; then
			kill -TERM ${pid} 2>${NULL}
			return
		fi
	done
}

start_stage_2()
{
	local args cmd dir pid count
	svc_wait 10 ${pidfile}

	if [ "${SV_CMD}" = "runsvdir" ]; then
		if [ "${OS_NAME}" = "FreeBSD" ]; then
			args=-fl
		else
			args=-ax
		fi
		if [ -e ${pidfile} ]; then
			pgrep ${args} ${SV_CMD} | while read pid cmd dir args; do
				if [ x${dir} = x${SV_RUNDIR} ]; then
					echo "${pid}" >${pidfile}
					break
				fi
			done
		fi
	fi

	sv-stage --default || sv-stage --single || svc_rsh
}

case ${SV_CMD} in
	(runsvdir)
:	${SV_OPTS:=log:...........................................................}
	;;
esac

pidfile="${SV_TMPDIR}/${SV_CMD}.pid"
init_stage()
{
if   [ "${1}" = "--svscan" ]; then
	[ -d "${SV_RUNDIR}" ] || svc_tmpdir
	if [ -e "${pidfile}" ]; then
		kill_svscan
	fi
	if [ "${2}" = "--foreground" ]; then
		ARGS=""  PRECMD="exec"
	else
		ARGS="&" PRECMD=""
	fi
	trap "rm -f ${pidfile}" SIGINT SIGQUIT SIGTERM
	echo $$ >${pidfile}
	eval ${PRECMD} ${__SV_CMD__} ${SV_RUNDIR} "${SV_OPTS}" ${ARGS}
elif [ "${1}" = "--sysinit" ]; then
	#
	# XXX: initialize temporary directory
	#
	if [ -n "${SV_SYSTEM}" ]; then
		[ -d "${SV_RUNDIR}" ] || svc_tmpdir
		return 0
	fi
	early_console
	svc_init
	[ "${2}" = "--background" ] || sv-stage --sysinit
elif [ "${1}" = "--default" ]; then
	[ -d "${SV_RUNDIR}" ] || svc_tmpdir
	#
	# Set up CGroup
	#
	if yesno "${SV_CGROUP}" && [ "${OS_NAME}" = "Linux" ]; then
		cgroup_add_service
	fi
	#
	# Bring up what left and stage-2 assuming `svcscan'
	# is ready when the following pidfile is present
	#
	if [ -e "${pidfile}" ]; then
		kill_svscan
		rm ${pidfile}
	fi
	#
	# XXX: This hackery is necessary to get the real pid;
	# this is used to send SIGCONT to runsvdir.
	#
	sh -c ". ${SV_LIBDIR}/sh/init-stage; start_stage_2;" &

	trap "rm -f ${pidfile}" SIGINT SIGQUIT SIGTERM
	echo $$ >${pidfile}
	exec /usr/bin/env - PATH=${PATH} ${__SV_CMD__} ${SV_RUNDIR} ${SV_OPTS}
	#
	# Drop into a rescue shell
	#
	svc_rsh
elif [ "${1}" = "--shutdown" -o "${1}" = "--reboot" ]; then
	ACTION=${1}
	case "${ACTION}" in
		(--reboot|--shutdown)  sv-stage ${ACTION};;
		(*) ACTION=--shutdown; sv-stage ${ACTION};;
	esac
	if [ -n "${SV_SYSTEM}" ]; then
		return 0
	fi

	#
	# CGroup clean up
	#
	if yesno "${SV_CGROUP}" && [ "${OS_NAME}" = "Linux" ]; then
		cgroup_remove_service
	fi
	${SV_LIBDIR}/sbin/shutdown --force ${ACTION} now
fi
}

case "${1}" in
	(--[idrs]*)
	begin "Starting ${1#--}\n"
	init_stage "${@}"
	end "${?}"
	;;
esac

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
