#!/bin/sh
#
# $Header:  /lib/sv/sh/runscript                         Exp $
# $Author: (c) 2015-6 tokiclover <tokiclover@gmail.com>  Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
# $Version: 0.6 2016/12/30 21:09:26                      Exp $
#

#
# ZSH compatibility
#
if [ -n "${ZSH_VERSION}" ]; then
	emulate sh
	NULLCMD=:
	setopt NO_GLOB_SUBST SH_WORD_SPLIT
	disable -r end
else
	case "$(set -o 2>/dev/null)" in
		(*posix*) set -o posix;;
	esac
fi

help_message() {
	cat <<-EOH
 usage: runscript [OPTIONS] SERVICE COMMAND [ARGUMENTS]
   COMMAND: add|del|desc|remove|reload|restart|start|stop|status|zap|cgroup_remove_service
   OPTIONS: [OPTIONS] SERVICE COMMAND [ARGUMENTS]
     -D, --nodeps     Disable dependencies1
     -g, --debug      Enable debug mode
     -r, --rs         Select runscript backend
     -s, --sv         Select supervision backend
     -h, --help       Print help and exit
EOH
${1+exit ${1}}
}

[ ${#} -ge 2 ] || help_message 1
while true; do
	case "${1}" in
		(-D|--node*) SVC_DEPS=0 ;;
		(-d|--deps)  SVC_DEPS=1 ;;
		(-r|--rs) SV_TYPE="rs" ;;
		(-v|--sv) SV_TYPE="sv" ;;
		(-g|--debug) set -x ;;
		(-h|--help) help_message 0 ;;
		(*) break ;;
	esac
	shift
done
:	${SV_LIBDIR:=${0%/sh/*}}
:	${SVC_NAME:=${1##*/}}
:	${name=${SVC_NAME}}
:	${__cmd__=${2}}
:	${SV_SVCDIR:=${1%/*}}
shift

if [ -z "${SV_TYPE}" ]; then
	[ -d "${1}" ] && SV_TYPE=sv || SV_TYPE=rs
fi

. "${0%/*}"/runscript-functions ||
	{ echo "Required file not found." >&2; exit 1; }
if [ ${#} -lt 1 ]; then
	error "Insufficient number of arguments"
	exit 2
fi
. ${SV_SVCDIR}/.opt/SVC_OPTIONS

#
# migrate to new sub-dirs
#
if [ ! -d ${SV_TMPDIR}/OPTS ]; then
	mkdir -p ${SV_TMPDIR}/ENVS ${SV_TMPDIR}/OPTS
	mv -f ${SV_TMPDIR}/SV_OPTIONS ${SV_TMPDIR}/ENV
	for a in ${SV_TMPDIR}/*_ENV; do
		b="${a##*/}"
		mv -f ${a} ${SV_TMPDIR}/ENVS/${b%_*}
	done
	for a in ${SV_TMPDIR}/*_OPTIONS; do
		b="${a##*/}"
		mv -f ${a} ${SV_TMPDIR}/OPTS/${b%_*}
	done
	a= b=
fi

#
# Handle command
#
case "${SV_TYPE}" in
	(rs) rs_cmd "${@}";;
	(sv)
		for var in COLUMNS SVC_DEPS SVC_DEBUG SV_RUNLEVEL SV_STAGE SV_TYPE \
			SV_SYSBOOT_LEVEL SV_SHUTDOWN_LEVEL SV_VERSION; do
			eval echo "${var}=\"\$${var}\""
		done >${SV_TMPDIR}/ENVS/${SVC_NAME}
		svc_cmd "${@}"
		;;
esac

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
