#!/bin/sh
#
# $Header:  /lib/sv/sh/runscript                         Exp $
# $Author: (c) 2015-6 tokiclover <tokiclover@gmail.com>  Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
# $Version: 0.6 2016/12/26 21:09:26                      Exp $
#

#
# ZSH compatibility
#
if [ -n "${ZSH_VERSION}" ]; then
	emulate sh
	NULLCMD=:
	setopt NO_GLOB_SUBST NULLGLOB SH_WORD_SPLIT
	disable -r end
elif [ -n "${BASH_VERSION}" ]; then
	shopt -qs nullglob
else
	case "$(set -o 2>/dev/null)" in
		(*posix*) set -o posix;;
	esac
fi

help_message() {
	cat <<-EOH
 usage: runscript [OPTIONS] SERVICE COMMAND [ARGUMENTS]
   COMMAND: add|del|desc|remove|reload|restart|start|stop|status|zap|cgroup_remove_service
   OPTIONS: [OPTIONS] SERVICE COMMAND [ARGUMENTS]
     -D, --nodeps     Disable dependencies1
     -g, --debug      Enable debug mode
     -r, --rs         Select runscript backend
     -s, --sv         Select supervision backend
     -h, --help       Print help and exit
EOH
${1+exit ${1}}
}

[ ${#} -ge 1 ] || help_message 1
while true; do
	case "${1}" in
		(-D|--node*) SVC_DEPS=0 ;;
		(-d|--deps)  SVC_DEPS=1 ;;
		(-r|--rs) SV_TYPE="rs" ;;
		(-v|--sv) SV_TYPE="sv" ;;
		(-g|--debug) set -x ;;
		(-h|--help) help_message 0 ;;
		(*) break ;;
	esac
	shift
done
:	${SV_LIBDIR:=${0%/sh/*}}
:	${SVC_NAME:=${1##*/}}
:	${name=${SVC_NAME}}
:	${__cmd__=${2}}

if [ -z "${SV_TYPE}" ]; then
	[ -d "${1}" ] && SV_TYPE=sv || SV_TYPE=rs
fi

case "${1}" in
	(*/sv/.stage-[0-3]*)
:	${SV_SVCDIR:=${1%/.stage-*}}
	;;
	(*)
:	${SV_SVCDIR:=${1%/*}}
	;;
esac
shift
. "${0%/*}"/runscript-functions ||
	{ echo "Required file not found." >&2; exit 1; }
if [ ${#} -lt 1 ]; then
	error "Insufficient number of arguments"
	exit 2
fi
. ${SV_SVCDIR}/.opt/SVC_OPTIONS

#
# Handle command
#
case "${SV_TYPE}" in
	(rs) rs_cmd "${@}";;
	(sv)
		export SVC_DEPS SVC_DEBUG SV_RUNLEVEL SV_STAGE SV_TYPE
		set | while read line; do
			case "${line}" in
				(COLUMNS=*|SVC_DEPS=*|SVC_DEBUG=*|SV_RUNLEVEL=*|SV_STAGE=*|SV_TYPE=*)
					printf "${line}\n";;
			esac
		done >${SV_TMPDIR}/ENVS/${SVC_NAME}
		svc_cmd "${@}"
		;;
esac

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
