.\"
.\" CopyLeft (c) 2016 tokiclover <tokiclover@gmail.com>
.\"
.\" Distributed under the terms of the 2-clause BSD License as
.\" stated in the COPYING file that comes with the source files
.\"
.pc
.TH SV-RUN 8 "2016-12-30" "0.13.0" "System Manager's Manual"
.SH NAME
sv-run \- manage runscript and supervision services
.SH DESCRIPTION
.B sv-run
is a utility to manage runscript and supervised services.
This utility is used in conjunction with a supervsion suite like
.B runit
,
.B s6
or
.B daemontools(-encore)
to get a fully supervised init-system and service-manager.
.SH SYNOPSIS
.B sv-run
.RB [\| OPTIONS \| ]
.RB \| SERVICE \|
.RB \| COMMAND \|
.RB [\| ARGUMENTS \|]

.B sv-run
.RB [\| \-h|\-\-help \|]
.RB [\| \-v|\-\-version \|]

.B SERVICE
name can be replaced by
.B scan
to update the dependency cache of the list of services passed as arguments
like \fBsv-run scan \fIspawn-fcgi.{lighttpd,nginx}\fR.

.B SERVICE
name can be replaced by the special use case
.B stage
to manage a whole bundle of services instead of a single service; for example,
`sv-run --default stage' to bring the system to default runlevel.
This usage is now superseded by
.B sv-stage
utility, see
.BR sv-stage (8)
manual page; and is thus discouraged.

.B NOTE:
If
.B service
is not installed in the default path, either add
.B $SV_LIBDIR/bin:$SV_LIBDIR/sbin
to
.B PATH
environment variable; or else, copy the symlink to
.I /sbin
for example to get the same behaviour; or else use
.B sv-run
instead because
.B service
is a just limited interfaces to manage service.

Do note that it's rather prefered and recommended to use
.B sv-run
command to manage services rather than using the service executable. And this
is more true for supervision services when dealing with dependencies and
virtual services. Starting a supervision service shall be done with
.B sv-run
binary instead of using `\fI@SYSCONFDIR@/sv/\fBSERVICE\fI/run \fBCOMMAND [ARGUMENTS]\fR'.

.SH OPTIONS
.TP
.B --(sysinit|sysboot|default|shutdown|reboot|single|nonetwork)
Select a particular init stage or runlevel (long options)
.TP
.B \-(0|1|2|3|4|5|6) | \-(p|s|N|d|S|b|r)
Select a particular init stage or runlevel (short options)
.TP
.B \-D|\-\-nodeps
Disable dependency tracking when starting/stopping services
.TP
.B \-g|\-\-debug
Enable debugging mode for services (shell tracing)
.TP
.B \-h|\-\-help
Print the help message
.TP
.B \-q|\-\-quiet
Suppress verbose message
.SH "SERVICE COMMANDS"
Standard LSB along with extra service commands are supported.
.TP
.B start
start a service if down or stopped (supervision service wait up to 10 seconds
by default to start a service.)
.TP
.B stop
stop a service if up or started (supervision service wait up to 10 seconds by
default to stop a service.)
.TP
.B restart
restart a service after stopping it if started (runscript service can define
a particular shell function for this purpose.)
.TP
.B remove
remove a supervised service from the running directory.
This command has no effect for runscript services.
.TP
.B status
report the status of service (if started or stopped.)
.TP
.B zap
remove the temporary files of a service to be able to start a fresh environment,
or restart a service if already started.
.TP
.B add
add a service to an sv-init.sh or runlevel (stage level argument is required.)
.TP
.B del
remove a service from an sv-init.sh or runlevel (stage level argument is required.)
.TP
.B cgroup_remove_service
remove the
.B Control Group PIDs
hierarchy after stopping a service. This command has no effect for runscript
services if not used with a daemon.
.B CGROUP_CLEANUP
environmenet variable can be enabled for automatic clean up.
.TP
.B new
add a new supervised service from a template. This command should be run with
`\fI@LIBDIR@/sv/bin/sv-config [--log] \fBSERVICE \fInew\fR'.
.TP
.B extra-commands
extra comands defined as shell functions and added to
.B SVC_COMMANDS
or
.B SVC_STARTED_COMMANDS
or
.B SVC_STOPPED_COMMANDS
environment variable. Any defined command can be used as a standard LSB command.
.TP
.B desc
print service description to standard output.
A command
.B name
argument can be passed to print the description of the command instead of the
description of the service, `sv-run udev desc reload' for example.
.B scan
update the dependency cache of a service. \fIsv-run scan\fB SERVICES\fR can be used
for a list of service instead.
.B down
send down command to the supervisor (supervision only)
.B up
send up command to the supervisor (supervision only)
.SH CONFIGURATION
See
.I @SYSCONFDIR@/sv.conf
for the global configuration file, or
.I @SYSCONFDIR@/sv.conf.d/\fBSERVICE\fR
for runscript particular services or
.I @SYSCONFDIR@/sv/\fBSERVICE\fI/OPTIONS\fB[.INSTANCE]\fR
for supervision services for the local configuration file,
and \fBsupervsion\fR(5) for settings related to
.B sv-run
service management.
.SH "RETURN VALUE"
.TP
.B 0
success (service already started/stopped)
.TP
.B 1
miscellaneous operational failures; or
a signal was sent to abort or terminate the program
.TP
.B 2
failure to find the requested service
.TP
.B 4
failure to lock a service lockfile for service command; or timed out when trying to
lock the lockfile.
.TP
.B 5
service keywords does not permit to \fI{stat,stop}\fR the service
.TP
.B 8
for
.I status
service command when a service is started and down (supervision only)
.TP
.B 16
for
.I status
service command when a service command failed
.TP
.B 32
for
.I status
service command when a service is waiting for the lockfile
.TP
.B errno
system call failure (fork...)
.TP
.B 255
execve system call failure
.SH "APPLICATION USAGE"
Some services are added to the service directory? Try starting them then.
It seems to work? Good, try to add them in a sv-init.sh or runlevel with
`\fIsv-run \fB--RUNLEVEL SERVICE \fIadd\fR'; and then regenerate the priority file
by running `\fIsv-stage \fB--RUNLEVEL\fR' and then checkout
\fISV_TMPDIR/deps/\fBRUNLEVEL\fR to see if the service is inserted
in the right place depending on the dependency definitions. Or better,
check out the file beforehand. It looks weird or the order changed dramatically?
Try removing the file altogether and try again. Else, it can be a case of cyclic
dependency definition. Major dependency redefinition is necessary.

.B NOTE:
Cyclical dependency definitions will cause dependency setup to fail when using
`\fIsv-run \fBSERVICE \fIstart\fR'
or service scheduling havoc in dependency tree files mentionned above.
.SH "FUTURE DIRECTIONS"
None.
.SH "SEE ALSO"
.RB supervision (5)
.RB sv-stage (8)
.RB sv-shutdown (8)
.SH AUTHORS
tokiclover <tokiclover@supervision.project>
.\"
.\" vim:fenc=utf-8:ft=groff:ci:pi:sts=2:sw=2:ts=2:expandtab:
.\"
