.\"
.\" CopyLeft (c) 2016 tokiclover <tokiclover@gmail.com>
.\"
.\" Distributed under the terms of the 2-clause BSD License as
.\" stated in the COPYING file that comes with the source files
.\"
.pc
.TH RS 8 "2016-12-28" "0.13.0" "SERVICE MANAGEMENT UTILITY"
.SH NAME
sv-stage \- utility to manage init-stage or runlevel
.SH DESCRIPTION
.B sv-stage
is a utility to manage init-stages or runlevel
for SystemV or BSD terminology.
This utility is used in conjunction with a supervsion suite like
.B runit
,
.B s6
or
.B daemontools(-encore)
to get a fully supervised init-system and service-manager. Otherwise, only
runscript would work out of the box if not. A supported supervision suite
can be configured to work with this utility by running
`\fI@LIBDIR@/sv/sbin/sv-config -s \fBSUPERVISOR\fR'.
And then, the recommended way to use this package is to use the included
`\fI@LIBDIR@/sv/sh/init-stage\fR' handler from `\fI@SYSCONFDIR@/runit/{1,2,3}\fR' for
example. Although, using
.B sv-stage
directly will still work when not using the init-system part of the package.
So, using it a replacement of
.B rc
would work in a standard SystemV or BSD system. Still, there are still some work
to be done to be realy compatible with BSD style service and runlevel management.
.SH SYNOPSIS
.B sv-stage
.RB [\| OPTIONS \| ]
.RB (\| RUNLEVEL \|)
.RB [\| ARGUMENTS \|]

.B sv-stage
.RB [\| \-h|\-\-help \|]
.RB [\| \-v|\-\-version \|]

Either an init-stage or runlevel is passed as a command line option or a command
line argument (like
.B rc
utility does.)
When a runlevel is passed as argument, not a command line option, runlevel will
be switched; e.g. requiring
.B single
runlevel when being in
.B default
runlevel will require stopping
.B default
runlevel beforehand.
Whereas, when using a runlevel as command line option, the action to
.I stop
or
.I start
can be appended to the command line as an argument. Some default actions are
hardcoded for specific runlevels; e.g.
.I start
for
.B sysinit
and
.I stop
for
.B reboot
or
.B shutdown.
.B NOTE:
.B single
runlevel is not stopped before switching to another runlevel in case somthing
happen. So, issueing a `\fBsv-stage --single \fIstop\fR' would be necessary to
stop
.B sulogin
or the rescue shell used as single user service.

.B NOTE:
If
.B rc
is not installed in the default path, either add
.B $SV_LIBDIR/bin:$SV_LIBDIR/sbin
to
.B PATH
environment variable; or else, copy the symlink to
.I /sbin
for example to get the same behaviour; or else use
.B sv-stage
instead because
.B service
or
.B rc
are a just limited interfaces to manage service or runlevel.

.SH SYSTEM-V OR BSD COMPATIBILITY RC USAGE
.B rc
.RB \| sysinit|sysboot|default|shutdown|reboot|single|nonetwork \|

Those runlevels can be required at bootup by appending a runlevel name to
.B softlevel
kernel command line argument like
.I softlevel=single
to request a runlevel.
And extra
.B noinit
kernel cmdline argument is also available to mark that comma separated list as
started to avoid starting them in
.I any
runlevels but \fIsysinit\fR, like
.I noinit=atd,cron
to avoid starting
.I cron
and
.I atd
services.

.B WARNING:
Services marked as started can be safely started after issuing
.B zap
service command. And some services will inevitably fail like networkfs.
Second,
.B (reboot|shutdown)
runlevels shall not be used when using
.I runit
or \fIs6\fR;
use \fI@LIBDIR@/sbin/sv-shutdown --(reboot|shutdown)\fR instead to properly
.B reboot
or
.B shutdown
a system by sending the proper signal to
.B PID
\fI1\fR (\fBINIT\fR) instead. Any other
.B init
that does not trigger a (reboot|shutdown) (by using
\fI@LIBDIR@/sv/sh/init-stage\fR)
can be used and then issue a \fIrc (reboot|shutdown)\fR to get almost the same
effect. However, using
.I sv-shutdown
has the same effect... so using it instead of
.B rc
binary is more safe when using a supported supervision backend.

.SH OPTIONS
.TP
.B (sysinit|sysboot|default|shutdown|reboot|single|nonetwork)
SystemV compatible runlevels used to start an init-stage
.TP
.B \-D|\-\-nodeps
Disable dependency tracking when starting/stopping services (IGNORED)
.TP
.B \-g|\-\-debug
Enable debugging mode for services (shell tracing) (DISABLED)
.TP
.B \-(0|1|2|3|4|5|6)
Select a particular init stage or runlevel
.TP
.B \-h|\-\-help
Print the help message
.TP
.B \-q|\-\-quiet
Suppress verbose message
.SH CONFIGURATION
See
.I @SYSCONFDIR@/sv.conf
for the global configuration file, or
.I @SYSCONFDIR@/sv.conf.d/\fBSERVICE\fR
for runscript particular services or
.I @SYSCONFDIR@/sv/\fBSERVICE\fI/OPTIONS\fB[.INSTANCE]\fR
for supervision services for the local configuration file,
and \fBsupervsion\fR(5) for settings related to
.B rs
service management.
.SH "RETURN VALUE"
.TP
.B 0
success
.TP
.B 1
miscellaneous operational failures (failure to read the dependency file...);
or
.B SIGUSR1
was sent to abort operation; or
a signal (\fBSIGTERM\fR ...) was sent to terminate the program
.TP
.B errno
system call failure (fork...)
.SH "APPLICATION USAGE"
Refer to 
.BR Brs (8)
section for more information.
.SH "FUTURE DIRECTIONS"
None.
.SH "SEE ALSO"
.BR rs (8)
.BR supervision (5)
.BR sv-shutdown (8)
.SH AUTHORS
tokiclover <tokiclover@supervision.project>
.\"
.\" vim:fenc=utf-8:ft=groff:ci:pi:sts=2:sw=2:ts=2:expandtab:
.\"
