.\"
.\" CopyLeft (c) 2016-2018 tokiclover <tokiclover@gmail.com>
.\"
.\" Distributed under the terms of the 2-clause BSD License as
.\" stated in the COPYING file that comes with the source files
.\"
.pc
.TH SVP 1 "2018-08-20" "0.14.0" "User Commands Manual"
.SH NAME
svp \-  run programm utility
.SH DESCRIPTION
.B svp
is a utility to run a programm with new software limits and environment.
This utility can be executed as
.B envdir
or
.B envuidgid
or
.B pgrphack
or
.B softlimit
or
.B setlock
or
.B setuidgid
or
.B setsid
with limited options.
See
.B SYNOPSIS
for more information.

.SH SYNOPSIS
.B svp
.RB [\| \-/ | \-\-chroot \ DIR \|]
.RB [\| \-b | \-\-name \ ARG \|]
.RB [\| \-c | \-\-core \ ARG \|]
.RB [\| \-d | \-\-data \ DIR \|]
.RB [\| \-e | \-\-envdir \ DIR \|]
.RB [\| \-f | \-\-output \ ARG \|]
.RB [\| \-G | \-\-egid \ GROUP \|]
.RB [\| \-U | \-\-euid \ USER[:GROUP] \|]
.RB [\| \-L | \-\-Lock \ FILE \|]
.RB [\| \-l | \-\-lock \ FILE \|]
.RB [\| \-m | \-\-memory \ ARG \|]
.RB [\| \-n | \-\-nice \ ARG \|]
.RB [\| \-o | \-\-open \ ARG \|]
.RB [\| \-p | \-\-proc \ DIR \|]
.RB [\| \-g | \-\-gig \ GROUP \|]
.RB [\| \-u | \-\-uid \ USER[:GROUP] \|]
.RB [\| \-s | \-\-sid \|]
.RB [\| \-P | \-\-pgrp \|]
.RB [\| \-0 | \-\-stdin \|]
.RB [\| \-1 | \-\-stdout \|]
.RB [\| \-2 | \-\-stderr \|]
.RB [\| \-V | \-\-verbose \|]
.BR \| PROG \|
.RB [\| ARGS \|]

.B svp
.RB [\| \-h | \-\-help \|]
.RB [\| \-v | \-\-version \|]

.B envdir
.RB \| DIR \|
.RB \| PROG·\|
.RB [\| ARGS \|]

.B envuidgid
.RB [\| \-U | \-u \ USER[:GROUP] \|]
.RB [\| \-G | \-g \ GROUP \|]
.RB \| PROG·\|
.RB [\| ARGS \|]

.B pgrphack
.RB \| PROG·\|
.RB [\| ARGS \|]

.B softlimit
.RB [\| \-c | \-\-core \ ARG \|]
.RB [\| \-d | \-\-data \ DIR \|]
.RB [\| \-f | \-\-output \ ARG \|]
.RB [\| \-m | \-\-memory \ ARG \|]
.RB [\| \-n | \-\-nice \ ARG \|]
.RB [\| \-o | \-\-open \ ARG \|]
.RB [\| \-p | \-\-proc \ DIR \|]
.RB \| PROG·\|
.RB [\| ARGS \|]

.B setlock
.RB [\| \-L | \-\-Lock \|]
.RB [\| \-l | \-\-lock \|]
.RB \| FILE \|
.RB \| PROG·\|
.RB [\| ARGS \|]

.B setuidgid
.RB [\| \-U | \-u \ USER[:GROUP] \|]
.RB [\| \-G | \-g \ GROUP \|]
.RB \| PROG·\|
.RB [\| ARGS \|]

.B setsid
.RB \| PROG·\|
.RB [\| ARGS \|]

.SH OPTIONS
.TP
.RB [\| \-/ | \-\-chroot \ DIR \|]
Change root directory to
.I DIR
.TP
.RB [\| \-b | \-\-name \ ARG \|]
Set the first vector argument, this is the default behavior
.TP
.RB [\| \-c | \-\-core \ ARG \|]
Set core size to
.I ARG
bytes
.TP
.RB [\| \-d | \-\-data \ DIR \|]
Set data size to
.I ARG
bytes
.TP
.RB [\| \-e | \-\-envdir \ DIR \|]
Use
.I DIR
environment directory
.TP
.RB [\| \-f | \-\-output \ ARG \|]
Set output file size to
.I ARG
bytes
.TP
.RB [\| \-G | \-\-egid \ GROUP \|]
Set effective group identity
.TP
.RB [\| \-U | \-\-euid \ USER[:GROUP] \|]
Set effective user, with optional group identity
.TP
.RB [\| \-L | \-\-Lock \ FILE \|]
Set a lock file without blocking
.TP
.RB [\| \-l | \-\-lock \ FILE \|]
Set a lock with blocking
.TP
.RB [\| \-m | \-\-memory \ ARG \|]
Set memory size to
.I ARG
bytes
.TP
.RB [\| \-n | \-\-nice \ ARG \|]
Set niceness to
.I ARG
increment
.TP
.RB [\| \-o | \-\-open \ ARG \|]
Set the maximum number of opened file to
.I ARG
which should be equal or above
.B \_POSIX_OPEN_MAX
.TP
.RB [\| \-p | \-\-proc \ DIR \|]
Set the maximum of user process to
.I ARG
.TP
.RB [\| \-g | \-\-gig \ GROUP \|]
Set the group identity
.TP
.RB [\| \-u | \-\-uid \ USER[:GROUP] \|]
Set the user identity, with an optional group identity
.TP
.RB [\| \-s | \-\-sid \|]
Use a new session
.TP
.RB [\| \-P | \-\-pgrp \|]
Use a new programm group
.TP
.RB [\| \-0 | \-\-stdin \|]
Close standard inoput
.TP
.RB [\| \-1 | \-\-stdout \|]
Close standard output
.TP
.RB [\| \-2 | \-\-stderr \|]
Close standard error
.TP
.RB [\| \-V | \-\-verbose \|]
Verbose message (IGNORED)
.TP
.B \| PROG \|
.RB [\| ARGS \|]
Program to execute with optional argument

.TP
.RB \| \-d | \-\-debug \|
.TP
.RB \| \-v | \-\-version \|
Print the version message
.TP
.RB \| \-h | \-\-help \|
Print the help message

.SH "RETURN VALUE"
.TP
.B 0
success
.TP
.B 1
miscellaneous operational failures

.SH "APPLICATION USAGE"
None.
.SH "FUTURE DIRECTIONS"
None.
.SH "SEE ALSO"
.BR sv-init (8),
.BR sv-run (8),
.BR sv-rcorder (8),
.BR supervision (5),
.BR sv-shutdown (8)
.SH AUTHORS
tokiclover <tokiclover@supervision.project>
.\"
.\" vim:fenc=utf-8:ft=groff:ci:pi:sts=2:sw=2:ts=2:expandtab:
.\"
