#!/bin/sh
#
# $Id:  @(#) cmd    0.3 2018/06/30 21:09:26                                Exp $
# $L$:  2-clause/new/simplified BSD                                        Exp $
#

#
# ZSH compatibility
#
if [ -n "${ZSH_VERSION}" ]; then
	emulate sh
	NULLCMD=:
	setopt SH_WORD_SPLIT
	disable -r end
fi

exec 2>&1

case "${0}" in
	(/*) head="${0%/*}"   ;;
	(*)  head="${PWD}/${0#./}"
	     head="${head%/*}";;
esac
:	${SVC_DIR=${head%/log}}
:	${SVC_NAME=${SVC_DIR##*/}}
case "${SVC_DIR}" in
	(*/etc/*)
:	${SV_SVCDIR=${SVC_DIR%/*}}
	;;
	(*/run/*|*/tmp/*)
:	${SV_RUNDIR=${SVC_DIR%/*}}
	;;
esac

case "${head}" in
	(*/log) __cmd_dir__=log;;
	(*)     __cmd_dir__="" ;;
esac
__cmd__="${0##*/}"
__svc__="${head%/$__cmd_dir__}"
unset head
SV_TYPE=sv
SV_LIBDIR=${SVC_DIR}/../../lib

trap "rm -f ${SV_TMPDIR}/envs/${SVC_NAME}" EXIT INT TERM QUIT
source "${SV_LIBDIR}"/sh/runscript-functions ||
	{ echo "Required file not found." >&2; exit 1; }


if [ "${__cmd__}" = "run" -o "${__cmd__}" = "finish" ]; then
	yesno "${__environ__}" || SOURCE ${SV_TMPDIR}/envs/${SVC_NAME}
	#
	# Use ENV dir(s) if requested
	#
	yesno "${ENV_DIR}" && svc_environ

	#
	# Set default getty options
	#
	case "${SVC_NAME}" in # SVC_NAME=$GETTY_TTY
	(*getty-tty*)
:	${PRE_CMD:=${__PRECMD__}}
	if [ "${__SV_NAM__}" = "runit" ]; then
	:	${PRE_OPTS:=-P}
	:	${FIN_CMD:=utmpset}
	:	${FIN_OPTS:=-w ${SVC_NAME#*-}}
	fi
	;;
	esac # SVC_NAME=$GETTY_TTY
fi # __cmd__=run

#
# Set a few specific log env variables
#
if [ "${__cmd_dir__}" = "log" ]; then
:	${SVC_LOGDIR:=${LOGDIR}/${SVC_NAME}}
:	${SVC_USER:=root}
:	${SVC_GROUP:=root}
:	${LOG_MODE:=0755}
:	${LOG_PROC:=gzip -nq}
:	${LOG_SIZE:=2048000}
:	${LOG_STAT:=}
:	${LOG_PREFIX:=${SVC_NAME}}
:	${LOG_CMD:=${__LOGCMD__}}
	#
	# Set default log options
	#
	if [ "${__SV_NAM__}" = "runit" ]; then
	:	${LOG_ARGS:="p${LOG_PREFIX}\ns${LOG_SIZE}\n!'${LOG_PROC}'"}
	:	${LOG_OPTS:=-tt ${SVC_LOGDIR}}
	else
	:	${LOG_ARGS:="s${LOG_SIZE} !'${LOG_PROC}'"}
	:	${LOG_OPTS:="T ${LOG_STAT:++^${LOG_STAT} =${SVC_LOGDIR}/status} ${LOG_ARGS}"}
	fi # __SV_NAM__
	unset LOG_PROC LOG_PREFIX LOG_STAT LOG_SIZE
fi # __cmd_dir__=log


#
# Handle [log/]{finish,run} & exec to the command
#
eval svc${__cmd_dir__:+_${__cmd_dir__}}_${__cmd__} "${@}"

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
