#!/bin/sh
#
# $Id:  @(#) cmd    0.2 2017/01/12 21:09:26                                Exp $
# $L$:  2-clause/new/simplified BSD                                        Exp $
#

#
# ZSH compatibility
#
if [ -n "${ZSH_VERSION}" ]; then
	emulate sh
	NULLCMD=:
	setopt SH_WORD_SPLIT
	disable -r end
fi

exec 2>&1

case "${0}" in
	(/*) head="${0%/*}"   ;;
	(*)  head="${PWD}/${0#./}"
	     head="${head%/*}";;
esac
:	${SVC_DIR=${head%/log}}
:	${SVC_NAME=${SVC_DIR##*/}}
case "${SVC_DIR}" in
	(*/etc/*)
:	${SV_SVCDIR=${SVC_DIR%/*}}
	;;
	(*/run/*|*/tmp/*)
:	${SV_RUNDIR=${SVC_DIR%/*}}
	;;
esac

case "${head}" in
	(*/log) __cmd_dir__=log;;
	(*)     __cmd_dir__="" ;;
esac
__cmd__="${0##*/}"
__svc__="${head%/$__cmd_dir__}"
unset head
SV_TYPE=sv
:	${SV_LIBDIR:=${SVC_DIR}/../../lib}

source "${SV_LIBDIR}"/sh/SVC_OPTIONS ||
	{ echo "Required file not found." >&2; exit 1; }
#
# Handle [log/]{finish,run} & exec to the command
#
eval svc${__cmd_dir__:+_${__cmd_dir__}}_${__cmd__} "${@}"

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
