#!/bin/sh
#
# $Header:  /etc/s6/crash                                Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

:	${SV_DIR:=/etc/s6}
:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
:	${SV_BACKEND=/etc/sv/.lib/sh/sv-backend}
if [ -f ${SV_BACKEND} ]; then
	source ${SV_BACKEND}
	svc_backend -i
fi
:	${SV_RUNDIR:=/run/service}

SV_CMD=s6-svscan
name=Init-Stage-3 begin "Re-Starting Supervision"
exec env - PATH=${PATH} ${SV_CMD:-s6-svscan} ${SV_OPTS} ${SV_RUNDIR}
end "${?}"

#
# FIXME: Reboot if the previous restart attempt failed
#
eval "${SV_DIR}"/finish -6 ||
${RS_SHELL:-${SHELL:-sh}} -im

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
