#!/bin/sh
#
# $Header:  /etc/s6/crash                                Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

:	${SV_DIR:=/etc/s6}
:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
:	${INIT_STAGE=/etc/sv/.lib/sh/init-stage}
:	${SV_RUNDIR:=/run/service}

if [ -x ${INIT_STAGE} ]; then
	exec ${INIT_STAGE} -2
fi

exec env - PATH=${PATH} s6-svscan ${SV_OPTS} ${SV_RUNDIR}
exec 2>&1
exec ${SHELL:-sh} -aim

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
