#!/bin/sh
#
# $Id:  @(#) /etc/s6/crash   0 2017/01/12 21:09:26                    Exp $
# $L$:  2-clause/new/simplified BSD License                           Exp $
#

:	${SV_RUNDIR:=/run/service}
PATH=/bin:/sbin:/usr/bin:/usr/sbin
INIT_STAGE=/lib/sv/sh/init-stage

if [ -x ${INIT_STAGE} ]; then
	exec ${INIT_STAGE} --default
fi

exec /usr/bin/env - PATH=${PATH} s6-svscan ${SV_OPTS} ${SV_RUNDIR}
exec 2>&1
exec ${SHELL:-sh} -aim

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
