#!/bin/sh
#
# $Header:  /etc/s6/finish                               Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

exec >/dev/console 2>&1

PATH=/bin:/sbin:/usr/bin:/usr/sbin
INIT_STAGE=/lib/sv/sh/init-stage
[ -d /lib/sv ] && PATH="/lib/sv/bin:/lib/sv/sbin:${PATH}"

case "${1}" in
	(-[6ir]|reboot)            RUNLEVEL=6 ACTION=reboot  ;;
	(-[07hpqst]|halt|poweroff) RUNLEVEL=0 ACTION=shutdown;;
esac
:	${RUNLEVEL:=0}
:	${ACTION:=shutdown}

if [ -x ${INIT_STAGE} ]; then
	${INIT_STAGE} "--${ACTION}" || sv-stage "--${ACTION}"
case "${ACTION}" in
	(reboot) reboot -f ;;
	(shutdown) halt -f ;;
esac
fi

s6-svc -D -T 10000 ${SV_RUNDIR}/*
RUNLEVEL="${RUNLEVEL}" rc "${ACTION}"

case "${ACTION}" in
	(reboot)
	reboot -p
	reboot -f
	;;
	(shutdown)
	halt -p
	halt -f
	;;
esac

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
