#!/bin/sh
#
# $Id:  @(#) /etc/s6/finish   0 2017/01/12 21:09:26                   Exp $
# $L$:  2-clause/new/simplified BSD License                           Exp $
#

exec >/dev/console 2>&1

PATH=/bin:/sbin:/usr/bin:/usr/sbin
SV_INIT_SH=/lib/sv/sh/sv-init.sh
SV_SHUTDOWN=/lib/sv/sbin/shutdown
[ -d /lib/sv ] && PATH="/lib/sv/bin:/lib/sv/sbin:${PATH}"

case "${1}" in
	(-[6ir]|reboot)            RUNLEVEL=6 ACTION=reboot  ;;
	(-[07hpqst]|halt|poweroff) RUNLEVEL=0 ACTION=shutdown;;
esac
:	${RUNLEVEL:=0}
:	${ACTION:=shutdown}

if [ -x ${SV_INIT_SH} ]; then
	${SV_INIT_SH} "${ACTION}" || sv-rc ${ACTION}
if [ -x ${SV_SHUTDOWN} ]; then
	${SV_SHUTDOWN} --${ACTION} now
fi
case "${ACTION}" in
	(reboot) reboot -f ;;
	(shutdown) halt -f ;;
esac
fi

s6-svc -D -T 10000 ${SV_RUNDIR}/*
RUNLEVEL="${RUNLEVEL}" rc "${ACTION}"

case "${ACTION}" in
	(reboot) reboot  ; reboot -f ;;
	(shutdown) halt -p ; halt -f ;;
esac

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
