#!/bin/sh
#
# $Header:  /etc/s6/finish                               Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

exec >/dev/console 2>&1

:	${SV_DIR:=/etc/s6}
:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
:	${INIT_STAGE=/etc/sv/.lib/sh/init-stage}

case "${1}" in
	(-[6ir])     LEVEL=6 ACTION=reboot  ;;
	(-[07hpqst]) LEVEL=0 ACTION=shutdown;;
esac
:	${LEVEL:=0}
:	${ACTION:=shutdown}

if [ -x ${INIT_STAGE} ]; then
	exec env - ACTION=${ACTION} LEVEL=${LEVEL} ${INIT_STAGE} -3
fi
s6-svc -D -T 10000 ${SV_RUNDIR}/*
RUNLEVEL=${LEVEL} rc ${ACTION}

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
