#!/bin/sh
#
# $Header:  /etc/s6/init-stage-1                         Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#
PATH=/bin:/sbin:/usr/bin:/usr/sbin
SV_INIT_STAGE=/lib/sv/sh/init-stage
SV_RUNDIR=/run/service
SV_SERVICE=/etc/service


mkdir -m 0755 -p "${SV_RUNDIR}"/.s6-svscan
for link in crash finish; do
	ln -f -s /etc/s6/${link} "${SV_RUNDIR}"/.s6-svscan/${link}
done

if [ -x ${SV_INIT_STAGE} ]; then
	${SV_INIT_STAGE} --sysinit
	exec ${SV_INIT_STAGE} --default
fi
RUNLEVEL=S rc sysinit
RUNLEVEL=S rc boot
#
# XXX: is this really necessary?
#
RUNLEVEL=3 rc default

case "${SV_RUNDIR}" in
	("${SV_SERVICE}")
	;;
	(*/run/*|*/tmp/*)
	rm -f -r "${SV_RUNDIR}"
	mkdir -p "${SV_RUNDIR}"
	cp -LRTp "${SV_SERVICE}" "${SV_RUNDIR}"
	;;
esac

exec /sur/bin/env - PATH=${PATH} s6-svscan ${SV_OPTS} ${SV_RUNDIR}
exec 2>&1
exec ${SHELL:-sh} -aim

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
