#!/bin/sh
#
# $Header:  /etc/s6/init-stage-1                         Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#
:	${SV_DIR=/etc/s6}
:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
:	${INIT_STAGE=/etc/sv/.lib/sh/init-stage}
:	${SV_RUNDIR:=/run/service}
:	${SV_SERVICE:=/etc/service}


mkdir -m 0755 -p "${SV_RUNDIR}"/.s6-svscan
for link in crash finish; do
	ln -f -s "${SV_DIR}"/${link} "${SV_RUNDIR}"/.s6-svscan/${link}
done

if [ -x ${INIT_STAGE} ]; then
	eval ${INIT_STAGE} -1
	exec ${INIT_STAGE} -2
fi
RUNLEVEL=S rc sysinit
RUNLEVEL=S rc boot
RUNLEVEL=3 rc default

case "${SV_RUNDIR}" in
	("${SV_SERVICE}")
	;;
	(*/run/*|*/tmp/*)
	rm -f -r "${SV_RUNDIR}"
	mkdir -p "${SV_RUNDIR}"
	cp -LRTp "${SV_SERVICE}" "${SV_RUNDIR}"
	;;
esac

exec env - PATH=${PATH} s6-svscan ${SV_OPTS} ${SV_RUNDIR}
exec 2>&1
exec ${SHELL:-sh} -aim

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
