#!/bin/sh
#
# $Header:  /etc/runit/1                                 Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
:	${INIT_STAGE=/lib/sv/sh/init-stage}

touch   /etc/runit/stopit
chmod 0 /etc/runit/stopit
[ -x ${INIT_STAGE} ] && exec ${INIT_STAGE} -1
RUNLEVEL=S rc sysinit

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
