#!/bin/sh
#
# $Header:  /etc/runit/1                                 Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
:	${SV_BACKEND=/etc/sv/.opt/sv-backend}
if [ -f ${SV_BACKEND} ]; then
	source ${SV_BACKEND}
	svc_backend -i
fi

name=OpenRC begin "System initialization"
RUNLEVEL=S rc sysinit
end "$?"

touch /etc/runit/stopit
chmod 0 /etc/runit/stopit

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
