#!/bin/sh
#
# $Header:  /etc/runit/2                                 Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
:	${INIT_STAGE=/lib/sv/sh/init-stage}
SV_OPTS='log:..................................................................'

[ -x ${INIT_STAGE} ] && SV_OPTS="${SV_OPTS}" exec ${INIT_STAGE} --default

RUNLEVEL=S rc boot
RUNLEVEL=3 rc default

:	${SV_RUNDIR:=/run/service}
:	${SV_SERVICE:=/etc/service}
case "${SV_RUNDIR}" in
	("${SV_SERVICE}")
	;;
	(*/run/*|*/tmp/*)
	rm -f -r "${SV_RUNDIR}"
	mkdir -p "${SV_RUNDIR}"
	cp -LRTp "${SV_SERVICE}" "${SV_RUNDIR}"
	;;
esac

exec env - PATH=${PATH} runsvdir ${SV_RUNDIR} ${SV_OPTS}
exec 2>&1
exec ${SHELL:-sh} -aim

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
