#!/bin/sh
#
# $Id:  @(#) /etc/runit/ctrlaltdel   0 2017/01/12 21:09:26            Exp $
# $L$:  2-clause/new/simplified BSD License                           Exp $
#

PATH=/bin:/sbin:/usr/bin:/usr/sbin
_PATH_WALL=
SV_SHUTDOWN=/lib/sv/sbin/shutdown

touch /etc/runit/stopit
chmod 100 /etc/runit/stopit
if [ -x ${SV_SHUTDOWN} ]; then
	[ -x /etc/runit/reboot ] && ARG=-r || ARG=-p
	${SV_SHUTDOWN} ${ARG} -l -m now
else

echo "System is going down in 3 seconds..." | ${_PATH_WALL:-busybox wall}
sleep 3

fi

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
