#!/bin/sh
#
# $Header:  /etc/runit/ctrlaltdel                        Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

:	${PATH=/bin:/sbin:/usr/bin:/usr/sbin}
sv_shutdown=/lib/sv/sbin/sv-shutdown

touch /etc/runit/stopit
chmod 100 /etc/runit/stopit
if [ -x ${sv_shutdown} ]; then
	${sv_shutdown} -h -m
else
	echo "System is going down" | busybox wall
	sleep 3
fi

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
