#!/bin/sh
#
# $Header:  /etc/sv/.opt/cmd                             Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

exec 2>&1

case "${0}" in
	(/*) head="${0%/*}"   ;;
	(*)  head="${PWD}/${0#./}"
	     head="${head%/*}";;
esac
:	${SVC_DIR=${head%/log}}
:	${SVC_NAME=${SVC_DIR##*/}}
case "${SVC_DIR}" in
	(*/run/*|*/tmp/*)
:	${SV_RUNDIR=${SVC_DIR%/*}}
	;;
	(*)
:	${SV_SVCDIR=${SVC_DIR%/*}}
	;;
esac
:	${RS_TYPE=sv}
# XXX: remove this to have the right PATH value (with no SV_SVCDIR prefix)
# for GRSecurity and SELinux security. This may be handy to test everything
# in place!!!
#
#:	${SV_LIBDIR=${SV_RUNDIR:-${SV_SVCDIR}}/.lib}

case "${head}" in
	(*/log) __cmd_dir__=log;;
	(*)     __cmd_dir__="" ;;
esac
unset head
__cmd__="${0##*/}"

source "${SVC_DIR}"/../.opt/SVC_OPTIONS ||
	{ echo "Required file not found." >&2; exit 1; }
#
# Handle [log/]{finish,run} & exec to the command
#
eval svc${__cmd_dir__:+_${__cmd_dir__}}_${__cmd__} "${@}"

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
