.\"
.\" CopyLeft (c) 2016-2018 tokiclover <tokiclover@gmail.com>
.\"
.\" Distributed under the terms of the 2-clause BSD License as
.\" stated in the COPYING file that comes with the source files
.\"
.pc
.TH SV-SHUTDOWN 8 "2018-07-20" "0.13.0" "System Manager's Utility"
.SH NAME
sv-shutdown \- utility to manage system
.BR halt (8)
,
.BR reboot (8)
and
.BR poweroff (8)
.SH DESCRIPTION
.B sv-shutdown
is a utility to manage system halt, poweroff and reboot when
.BR sv-rc (8)
is used as init-system.
This utility can be used with SystemV or BSD utility name aliases, namely,
.BR halt (8)
,
.BR poweroff (8)
,
.BR reboot (8)
and
.BR shutdown (8)
to adopt the behaviour of the said utility. This means that, the utility will
halt the system if called as
.BR halt (8)
, poweroff if called as
.BR poweroff (8)
, put the system to single runlevel if called as
.BR shutdown (8)
without argument.
.B sh-shutdown
requires that an action
.RB (\| \-\-poweroff | \-\-reboot | \-\-halt | \-\-cancel | \-\-message \|)
or
.RB (\| \-p | \-r | \-h | \-c | \-m \|)
to be specified.
.SH SYNOPSIS
.B sv-shutdown
.RB [\| OPTIONS \| ]
.RB (\| ACTION \|)
.RB (\| TIME \|)
.RB [\| MESSAGE \|]

The
.B TIME
argument is only required when called as the
.B shutdown (8)
alias.
And the
.B ACTION
is reuired only if called as \fBsv-shutdown\fR,
the other aliases have default actions as previously said above.

.B shutdown
.RB [\| \-c | \-m | \-h | \-p | \-r \|]
.RB \| TIME \|
.RB [\| MESSAGE \|]

.RB (\| halt | poweroff | reboot \|)
.RB [\| -n \|]
.RB [\| -p \|]
.RB [\| -q \|]

.SH OPTIONS
.TP
.RB \| \-6 | \-r | \-\-reboot \|
Reboot the system after shutdown
.TP
.RB \| \-0 | \-s | \-\-shutdown \|
Action to shutdown the system
.TP
.RB \| \-H | \-h | \-\-halt \|
Action to halt the system (equivalent to \fB--poweroff\fR unless \fB--force\fR is used)
.TP
.RB \| \-P | \-p | \-\-poweroff \|
Action to poweroff the msystem (equivalent to \fB--shutdown\R unless the
.B shutdown
alias is used)
.TP
.RB \| \-f | \-\-fast \|
"Fast boot", skip
.RB fsck (8)
on reboot
.TP
.RB \| \-F | \--fsck \|
Force filesystem check
.RB fsck (8)
on reboot
.TP
.RB \| \-n | \-\-nosync \|
Do not synchronize filesystems before calling
.B shutdown
(the default is to synchronize filesystems)
.TP
.RB \| \-l | \-\-syslog \|
Log shutdown action to system logger (default) for message broadcast mode
.TP
.rB \| \-c | \-\-cancel \|
Cancell a previous and waiting call to \fBshutdown\fR
.TP
.RB \| \-m | \-\-message \|
Broadcast only the message to users
.TP
.RB \| \-q | \-\-force \|
Force a system {halt,poweroff,reboot} without calling shutdown
(this option force a shutdown cancellation as well)
.TP
.RB (\| TIME \|)
The time to shutdown the system can be either
.I now
or specified as \fI+\fBmintues\fR (number of minutes to wait); or else in
.RB [\| yymmdd \|]hhmm \|
format with an optional \fIyear\fR, \fImonth\fR and \fIday\fR which default to the current
system values (\fB[\|h\|]h:mm\fR format is also supported when only the
.I hour
and
.I minute
are specified.
.TP
.RB [\| MESSAGE \|]
Warning message to broadcast; any other argument is included as a new line of
message to be broadcasted. The
.I message
is broadcasted starting at 10 hours before system shutdown; and will become more
frequent as the deadline approaches. Login will be disabled 5 minutes before
system shutdown by creating
.I @_PATH_NOLOGIN@
and writting the broadcasted message.
If a user attempts to log in,
.BR login (1)
prints its contents and exits. The file is removed just before
.B shutdown
exits.

At shutdown time, a message is written to the system log, containing the time of
shutdown, the person who initiated the shutdown and the reason of the shutdown.
The appropriate signal is sent to
.I init
(PID \fI1\fR), namely
.I runit-init
or
.I s6-svscan
via
.I s6-svscanctl
or else,
.I sv-rc
is called directly to shutdown the system which imply a latter call with
.I --force
of
.I -q
option to force system shutdown once the services are stopped.

A scheduled shutdown can be cancelled by sending
.B SIGUSR1
to the utility. In fact sending any of
.B SIG{INT,TERM,QUIT}
will cancel a scheduled shutdown; but the usage of
.B SIGUSR1
is more safe when other shutdown utilities are used (SystemV or BSD utilities).
However, cancelling a scheduled shutdown can be done by calling the utility with
.I --cancel
or
.I -c
option.
.TP
.B \-u \| \-\-usage
Print the help message
.TP
.B \-v \| \-\-version
Print version string message

.SH FILES
.TP
.B /var/run/utmp
Record of users currently logged in
.TP
.B /var/log/wtmp
Record of all login and logout
.TP
.B @LIBDIR@/sv/sh/SV-CONFIG
Commands definition for supervision (services)

.SH "RETURN VALUE"
.TP
.B 0
success
.TP
.B 1
miscellaneous operational failures (failure to read the dependency file...);

.SH "APPLICATION USAGE"
Refer to
.BR sv-rc (8)
for more information.
.SH "FUTURE DIRECTIONS"
None.
.SH "SEE ALSO"
.BR supervision (5)
.BR sv-init (8),
.BR sv-run (8)
.BR sv-rc (8)
.SH AUTHORS
tokiclover <tokiclover@supervision.project>
.\"
.\" vim:fenc=utf-8:ft=groff:ci:pi:sts=2:sw=2:ts=2:expandtab:
.\"
