#!/bin/sh
#
# $Header:  /etc/sv/.bin/mdev-start-dev                  Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
# $Version: 0.2 2015/02/24 21:09:26                      Exp $
#

:	${MDEV_CMD:=/sbin/mdev}
:	${MDEV_LOGFILE:=/run/mdev.log}
if command -v die >/dev/null 2>&1; then
	source "${0%/*}"/../.opt/functions
fi
name=mdev

mdev_start_dev()
{
	if ! [ -x ${MDEV_CMD} ]; then
		if type -p busybox >/dev/null 2>&1; then
			MDEV_CMD="$(type -p busybox) mdev"
		else
			die "Failed to setup mdev."
		fi
	fi
	if ! grep -Eq '/dev .*tmpfs' /proc/mounts; then
		mount -t tmpfs -o exec,nosuid,mode=755,size=10M dev /dev ||
			die "Failed to setup tmpfs."
	fi
	if [ -n "${MDEV_DEBUG}" ]; then
		touch ${MDEV_LOGFILE}
		ln -s ${MDEV_LOGFILE} /dev/mdev.log
	fi
	touch /dev/mdev.seq
	echo "${MDEV_CMD}" >/proc/sys/kernel/hotplug
	#
	# Populate /dev
	#
	${MDEV_CMD} -s
	#
	# Seed /dev with necessary device nodes
	#
	mdev_seed_dev
}

mdev_seed_dev()
{
	#
	# Check out/Create some required nodes
	#
	[ -c /dev/console ] || mknod /dev/console c 5 1
	[ -c /dev/tty1    ] || mknod /dev/tty1    c 4 1
	[ -c /dev/null    ] || mknod /dev/null    c 1 3
	[ -d /lib/mdev/devices ] && cp -RPp /lib/mdev/devices/* /dev 2>/dev/null
	#
	# Handle std{out,in,err} (not provided by sysfs)
	#
	ln -fns /proc/self/fd /dev/fd
	ln -fns fd/0     /dev/stdin
	ln -fns fd/1     /dev/stdout
	ln -fns fd/2     /dev/stderr
	[ -e /proc/kcore ] && ln -fns /proc/kcore /dev/core
	#
	# Create required directories
	#
	mkdir -p /dev/pts /dev/shm
}

if [ "${0##*/}" = "mdev-start-dev" ]; then
	mdev_start_dev "${@}"
fi

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
