#!/bin/sh
#
# $Header:  /etc/sv/.bin/rs                              Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
# $Version: 0.2 2015/04/22 21:09:26                      Exp $
#

usage() {
	cat <<-EOH
 usage: rs [OPTIONS] COMMAND SERVICE [ARGUMENTS]
   COMMAND: add|del|restart|start|stop|status|zap
   OPTIONS: [OPTS] COMMAND SERVICE [ARGS]
     -D, --nodeps     Disable dependencies
     -g, --debug      Enable debug mode
   OPTIONS: [OPTS] stage [ARGS]
     -0, --sysinit    Select stage-0
     -1, --boot       Select stage-1
     -2, --default    Select stage-2
     -3, --shutdown   Select stage-3
     -h, --help       Help/Exit
EOH
${1+exit ${1}}
}

[ ${#} -ge 2 ] || usage 1
ARGS="$(getopt \
	-o 0123Dgh -l debug,help,nodeps \
	-l boot,default,shutdown,sysinit \
	-s sh -n rs -- "${@}")"
[ ${?} -eq 0 ] || usage 1
eval set -- ${ARGS}

while true; do
	case "${1}" in
		(-D|--node*) SVC_NODEPS=0 ;;
		(-g|--debug) set -x ;;
		(-h|--help) usage 0 ;;
		(-0|--sysin*) LVL=0 ;;
		(-1|--boot)   LVL=1 ;;
		(-2|--defau*) LVL=2 ;;
		(-3|--shutd*) LVL=3 ;;
		(*) shift;  break   ;;
	esac
	shift
done

case "${0}" in
	(/*) head="${0%/*}"   ;;
	(*)  head="${PWD}/${0#./}"
	     head="${head%/*}";;
esac
case "${1}" in
	(*rs.d/*)
:	${SVC_NAME:=${1##*/}}
:	${CMD=${2}}
	;;
	(*)
case "${2}" in
	(stage)
:	${SRC_OPTS=}
:	${CMD=${1} ${2} '${RS_STAGE}'}
	;;
	(*)
:	${CMD=${1}}
	;;
esac
:	${SRC_OPTS=-d}
:	${SVC_NAME=${2}}
	;;
esac
case "${3}" in
	(*-[0123]) LVL=${3#*-}; shift;;
esac
shift 2
:	${RS_STAGE:=stage-2}
:	${RS_SVCDIR:=${head%/sv*}/rs.d}
:	${RS_RUNDIR:=${RS_SVCDIR}/${RS_STAGE}}
:	${SV_SVCDIR:=${head%/.bin}}
:	${name=${SVC_NAME}}
unset head

ARGS=-C
source "${SV_SVCDIR}"/.opt/SVC_OPTIONS ||
	{ echo "Required file not found." >&2; exit 1; }
#
# Handle command
#
eval set -- ${CMD} "${@}"
eval rs_cmd "${@}"

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
