#!/bin/sh
#
# $Header:  /etc/sv/.bin/supervision-backend             Exp $
# $License: 2-clause/new/simplified BSD                  Exp $
#

usage() {
	cat <<-EOH
 usage: ${0##*/} daemontools[-encore]|runit|s6
EOH
}

SIGNALS='SIGSTRT SIGSTOP SIGONCE SIGPAUSE SIGCONT SIGHUP SIGALRM SIGINT
	SIGTERM SIGKILL SIGEXIT SIGQUIT SIGUSR1 SIGUSR2 SIGWTUP SIGWDWN'
BINS='envdir envuidgid fghack pgrphack setlock setuidgid softlimit'
CMDS='SV_CMD SVCCMD CHKCMD STACMD LOGCMD'

case "${1}" in
	(daemontools*|runit|s6) SV_OPT=${1};;
	(*) echo -e " Invalid supervision backend.\n" >&2
		usage; exit 1;;
esac

case ${SV_OPT} in
	(daemontools)
		BIN='' PREFIX=''
		;;
	(daemontools-encore)
		BIN='' PREFIX=''
		SIGQUIT=-q SIGUSR1=-1 SIGUSR2=-2
		;;
	(runit)
		BIN=chpst CMDS="${CMDS} PRECMD" PREFIX='' SIGNALS="${SIGNALS} SIGRLD"
		SIGWTUP="'-w 10 up'" SIGWDWN="'-w 10 down'"
		SIGSTRT=up SIGSTOP=down SIGONCE=once SIGPAUSE=pause SIGCONT=cont
		SIGHUP=hup SIGALRM=alarm SIGINT=interrupt SIGQUIT=quit SIGUSR1=1
		SIGUSR2=2 SIGTERM=term SIGKILL=kill SIGEXIT=exit SIGRLD=reload
		SV_CMD=runsvdir SVCCMD=sv CHKCMD="'sv check'" STACMD=sv PRECMD=chpst LOGCMD=svlogd
		;;
	(s6)
		BIN='' PREFIX=s6- SIGWTUP="'-U -T 10000'" SIGWDWN="'-D -T 10000'"
		SIGQUIT=-q SIGUSR1=-1 SIGUSR2=-2
		SV_CMD=s6-svscan SVCCMD=s6-svc CHKCMD=s6-svok STACMD=s6-svsat LOGCMD=s6-log
		;;
	(*) usage; exit 2;;
esac
:	${SIGSTRT:=-u}
:	${SIGSTOP:=-d}
:	${SIGONCE:=-o}
:	${SIGPAUSE:=-p}
:	${SIGCONT:=-c}
:	${SIGHUP:=-h}
:	${SIGALRM:=-a}
:	${SIGINT:=-i}
:	${SIGTERM:=-t}
:	${SIGKILL:=-k}
:	${SIGEXIT:=-x}
:	${SVCCMD:=svc}
:	${SV_CMD:=svscan}
:	${CHKCMD:=svok}
:	${STACMD:=svstat}
:	${LOGCMD:=multilog}
:	${SV_SVCDIR:=/etc/sv}

for bin in ${BINS}; do
	ln -f -s $(type -p ${PREFIX}${BIN:-${bin%:*}}) ${SV_SVCDIR}/.bin/${bin#*:}
done

for env in SV_OPT ${CMDS} ${SIGNALS}; do
	eval echo ${env}=\"\${${env}}\"
	unset ${env}
done > "${SV_SVCDIR}"/.opt/SVC_BACKEND

unset BINS CMDS PREFIX SIGNALS bin env

#
# vim:fenc=utf-8:ft=sh:ci:pi:sts=0:sw=4:ts=4:
#
